### ISSUE TITLE
ElectricalSeriesIOTest not passing

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#103]
I don't know what is causing this bug

```matlab
Verification failed in tests.system.ElectricalSeriesIOTest/testOutToPyNWB.

    ----------------
    Test Diagnostic:
    ----------------
    E
    ======================================================================
    ERROR: testInFromMatNWB (PyNWBIOTest.ElectricalSeriesIOTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1140, in construct
        obj = cls(**kwargs)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 991, in __init__
        col = col_dict[name]
    KeyError: 'x'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/bendichter/dev/matnwb/+tests/+system/PyNWBIOTest.py", line 32, in testInFromMatNWB
        matfile = io.read()
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 33, in read
        container = self.__manager.construct(f_builder)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 195, in construct
        result = self.__type_map.construct(builder, self)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1556, in construct
        return attr_map.construct(builder, build_manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1116, in construct
        subspecs = self.__get_subspec_values(builder, self.spec, manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1060, in __get_subspec_values
        self.__get_sub_builders(groups, spec.groups, manager, ret)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1098, in __get_sub_builders
        ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1060, in __get_subspec_values
        self.__get_sub_builders(groups, spec.groups, manager, ret)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1090, in __get_sub_builders
        sub_builder = self.__flatten(sub_builder, subspec, manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1103, in __flatten
        tmp = [manager.construct(b) for b in sub_builder]
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1103, in <listcomp>
        tmp = [manager.construct(b) for b in sub_builder]
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 195, in construct
        result = self.__type_map.construct(builder, self)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1556, in construct
        return attr_map.construct(builder, build_manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1116, in construct
        subspecs = self.__get_subspec_values(builder, self.spec, manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1061, in __get_subspec_values
        self.__get_sub_builders(datasets, spec.datasets, manager, ret)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1100, in __get_sub_builders
        ret[subspec] = manager.construct(sub_builder)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 195, in construct
        result = self.__type_map.construct(builder, self)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1556, in construct
        return attr_map.construct(builder, build_manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1116, in construct
        subspecs = self.__get_subspec_values(builder, self.spec, manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1026, in __get_subspec_values
        ret[attr_spec] = manager.construct(attr_val)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 195, in construct
        result = self.__type_map.construct(builder, self)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1556, in construct
        return attr_map.construct(builder, build_manager)
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 381, in func_call
        return func(self, **parsed['args'])
      File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1144, in construct
        raise_from(Exception(msg), ex)
      File "<string>", line 3, in raise_from
    Exception: Could not construct DynamicTable object
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.059s
    
    FAILED (errors=1)

    ------------------
    Stack Information:
    ------------------
    In /Users/bendichter/dev/matnwb/+tests/+system/PyNWBIOTest.m (PyNWBIOTest.testOutToPyNWB) at 15
```

**Comment by bendichter** [comment]
depends on https://github.com/NeurodataWithoutBorders/pynwb/issues/815
