### ISSUE TITLE
PhotonSeriesIOTest not passing

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/matnwb#105]
```matlab
================================================================================
Verification failed in tests.system.PhotonSeriesIOTest/testOutToPyNWB.

    ----------------
    Test Diagnostic:
    ----------------
    /Users/bendichter/dev/pynwb/src/pynwb/image.py:80: DeprecationWarning: bits_per_pixel is no longer used
      warnings.warn("bits_per_pixel is no longer used", DeprecationWarning)
    E
    ======================================================================
    ERROR: testInFromMatNWB (PyNWBIOTest.PhotonSeriesIOTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/bendichter/dev/matnwb/+tests/+system/PyNWBIOTest.py", line 33, in testInFromMatNWB
        matcontainer = self.getContainer(matfile)
      File "/Users/bendichter/dev/matnwb/+tests/+system/PyNWBIOTest.py", line 170, in getContainer
        return file.get_acquisition(self.container.name)
    AttributeError: 'NoneType' object has no attribute 'name'
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.061s
    
    FAILED (errors=1)

    ------------------
    Stack Information:
    ------------------
    In /Users/bendichter/dev/matnwb/+tests/+system/PyNWBIOTest.m (PyNWBIOTest.testOutToPyNWB) at 15
================================================================================
.
================================================================================
Error occurred in tests.system.PhotonSeriesIOTest/testInFromPyNWB and it did not run to completion.

    ---------
    Error ID:
    ---------
    'MATLAB:getReshapeDims:notSameNumel'

    --------------
    Error Details:
    --------------
    Error using reshape
    To RESHAPE the number of elements must not change.
    
    Error in tests.system.RoundTripTest/verifyContainerEqual (line 73)
                            trueval = reshape(trueval, size(val2));
    
    Error in tests.system.PyNWBIOTest/testInFromPyNWB (line 28)
          testCase.verifyContainerEqual(pycontainer, matcontainer);
================================================================================
```

**Comment by bendichter** [comment]
depends on https://github.com/NeurodataWithoutBorders/pynwb/issues/815
